source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in Sampleproject-BookList.gemspec

gem  'sinatra'

gem 'json'

gem 'mongoid'

gemspec
